name: Build Android APK
on:
  push:
    branches: [ main ] # или master, укажите вашу ветку

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Обновлено до v4 (актуальная стабильная версия)
    - uses: actions/checkout@v4
    
    # Обновлено до v4 (актуальная стабильная версия)
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    # Обновлено до v3 (поддерживает новые версии Node)
    - name: Set up Flutter
      uses: subosito/flutter-action@v3
      with:
        flutter-version: 'stable'
        
    # Сборка Flutter
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk --release

    # Обновлено до v4
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        
